### ISSUE TITLE
404 link on github front page https://github.com/Leont/const-fast to http://search.cpan.org/~leont/Const/

### ISSUE THREAD

**Issue by pmorch** [Leont/const-fast#7]
The [github front page](https://github.com/Leont/const-fast) has a 404 link to: http://search.cpan.org/~leont/Const/ . I think it is in the "description" of the repository. Perhaps that should point to metacpan: https://metacpan.org/release/Const-Fast instead.

I post it here and not in RT, because it really is isolated to the github repository.

**Comment by Leont** [comment]
Thanks, fixed
